Lesson 1: Add Adminer Docker container config
UIIf/fefu_backend_3_6 pull request #1
Opened 2022-03-16 12:55 UTC by UIIf

2022-03-23 02:36 UTC, chrn-feip requested changes
Несогласованность у вас получилась в том, что добавили в качестве GUI, и в том, о чём написали в сообщении коммита. Поправьте тоже, пожалуйста, git commit --amend в комощь.

2022-03-23 02:36 UTC, chrn-feip commented on fefu_app/docker-compose.yml
> +    bitnami_postgres:
Этот контейнер вам зачем? PostgreSQL уже установлен в контейнере pgsql.

2022-03-23 02:36 UTC, chrn-feip commented on fefu_app/docker-compose.yml
> +            - '${FORWARD_PGADMIN_PORT:-8080}:80'
Когда вы добавляете в код (или иные места) упоминание новых переменных окружения, тогда же надо и сами переменные объявить, с дефолтными или пустыми значениями. Делается это в файле .env.example. Тоже должно попасть в этот коммит.

2022-03-25 09:02 UTC, UIIf commented
Внесены изменения

2022-03-25 09:02 UTC, closed without merging