Task 3
UIIf/fefu_backend_3_6 pull request #4
Opened 2022-04-16 02:13 UTC by UIIf

2022-04-21 08:30 UTC, tonighty requested changes

2022-04-21 08:30 UTC, tonighty commented on fefu_app/app/Policies/NewsPolicy.php
> +class NewsPolicy
не нужно

2022-04-21 08:30 UTC, tonighty commented on fefu_app/app/Http/Requests/StoreNewsRequest.php
> +class StoreNewsRequest extends FormRequest
не нужно

2022-04-21 08:30 UTC, tonighty commented on fefu_app/app/Http/Requests/UpdateNewsRequest.php
> +class UpdateNewsRequest extends FormRequest
не нужно

2022-05-02 09:50 UTC, chrn-feip commented
@UIIf зачем вы удаляете комменты ревьювера? Если были внесены правки, то делайте резолв, а не удаление. Сейчас  непонятно, какие правки требовались и что именно надо допроверить, придётся проверять всё заново.

2022-05-02 09:50 UTC, chrn-feip commented
@tonighty призываю тебя

2022-05-02 09:58 UTC, UIIf commented
Нужно было удалить 3 файла, что я и сделал, но гитхаб решил что я не исправил ошибку, зря удалил

2022-05-02 10:00 UTC, UIIf commented
> @UIIf зачем вы удаляете комменты ревьювера? Если были внесены правки, то делайте резолв, а не удаление. Сейчас  непонятно, какие правки требовались и что именно надо допроверить, придётся проверять всё заново.

Нужно было удалить 3 файла, что я и сделал, но гитхаб решил что я не исправил ошибку, зря удалил

2022-05-02 20:22 UTC, tonighty approved these changes

2022-05-02 20:23 UTC, merged