Task 4
UIIf/fefu_backend_3_6 pull request #5
Opened 2022-04-17 08:17 UTC by UIIf

2022-05-02 09:52 UTC, chrn-feip commented
Сделайте, пожалуйста, нормальный ребейз, чтобы тут остался только один коммит - с ДЗ4 - и только файлы, в которых были связанные с заданием изменения, см. Files changed

2022-05-02 09:52 UTC, chrn-feip requested changes
Не буду смотреть изменения по ДЗ, пока не избавите PR от лишнего.

2022-05-14 02:26 UTC, UIIf commented
> А когда вы тут наведете порядок?

Я все верно сделал?

2022-05-17 08:25 UTC, chrn-feip commented
> > А когда вы тут наведете порядок?
> 
> Я все верно сделал?

Неверно.
Сделайте иначе: переключитесь на master, git pull, сделайте новую ветку, а в ней сделайте git cherry-pick <SHA1 коммита> для коммитов с ДЗ 4 (кроме delete garbage, он не верен). Хэш коммита можете найти и скопировать тут же, в списке коммитов PR. После этого проверьте, что всё работает, сделайте пуш и поменяйте from ветку в PR

2022-05-17 11:10 UTC, chrn-feip requested changes

2022-05-17 11:10 UTC, chrn-feip commented on fefu_app/api-docs.json
> +                    "appeal"
Где этот тег в конфиге openapi.php?

2022-05-22 04:52 UTC, closed without merging