Lesson 6: create oauth
UIIf/fefu_backend_3_6 pull request #9
Opened 2022-05-23 06:57 UTC by UIIf

2022-05-23 07:56 UTC, chrn-feip requested changes

2022-05-23 07:56 UTC, chrn-feip commented on fefu_app/app/Http/Controllers/Api/AuthApiController.php
> +        if ($user) {
$user !== null

2022-05-23 07:56 UTC, chrn-feip commented on fefu_app/app/Http/Controllers/Api/AuthApiController.php
> +            $user = User::createFromRequest($user, $data);
Наверное, changeFromRequest?

2022-05-23 07:56 UTC, chrn-feip commented on fefu_app/app/Http/Requests/BaseRegisterFormRequest.php
> +                ->where('email', $this->request->get('email'))
$this->validated('email')

2022-05-23 07:56 UTC, chrn-feip commented on fefu_app/app/Http/Controllers/Web/AuthWebController.php
> +        $user = User::createFromRequest($data);
Здесь актуальна та же проверка с create/change, которую вы написали в Api/AuthController

2022-05-23 07:56 UTC, chrn-feip commented on fefu_app/app/Http/Controllers/Api/AuthApiController.php
> +            $user->app_logged_in_at = Carbon::now();
Это актуально и логина в веб-контроллере

2022-05-23 09:27 UTC, UIIf commented on fefu_app/app/Http/Controllers/Api/AuthApiController.php
> +        if ($user) {
Разве тут не работает так что, что угодно кроме NULL, уже является true, как в ++ например

2022-05-23 11:13 UTC, chrn-feip commented on fefu_app/app/Http/Controllers/Api/AuthApiController.php
> +        if ($user) {
Это неявная проверка, бе учёта типов. Лучше придерживаться строгих условий с проверкой типа, иначе можно упустить ошибку.

2022-05-25 11:18 UTC, chrn-feip requested changes

2022-05-25 11:18 UTC, chrn-feip commented on fefu_app/app/Http/Requests/BaseRegisterFormRequest.php
> +            if(!$this->validated('email'))
Нет. Проверка не нужна. Это же метод after, т.е. валидация уже прошла. Я имела в виду замену конструкции $this->request->get('email') на $this->validated('email'), потому что это одно и тоже и вам не нужно лезть заново в request. А проверка смысла не имеет в таком виде, потому не выполнится, если почта заполнена хоть чем-нибудь.

2022-05-26 02:24 UTC, merged